import { OrderStatus } from "@/enums";
import { orderSchema } from "@/validation/order";
import { z } from "zod";

const mockOrdersData = [
    {
        id: 1,
        customerId: 1,
        invoiceId: "INV-2024-001",
        status: OrderStatus.Pending,
        deliveryMethod: "standard",
        deliveryCountry: "Netherlands",
        deliveryFirstname: "Eddie",
        deliveryLastname: "Lake",
        deliveryCompany: "Lake Solutions BV",
        deliveryAddress: "Keizersgracht 123",
        deliveryPostalcode: "1015 CJ",
        deliveryCity: "Amsterdam",
        deliveryPhonenumber: "+31 20 123 4567",
        invoiceCountry: "Netherlands",
        invoiceFirstname: "Eddie",
        invoiceLastname: "Lake",
        invoiceCompany: "Lake Solutions BV",
        invoiceCOCNumber: "12345678",
        invoiceAddress: "Keizersgracht 123",
        invoicePostalcode: "1015 CJ",
        invoiceCity: "Amsterdam",
        invoicePhonenumber: "+31 20 123 4567",
        createdAt: new Date("2024-11-10T10:30:00Z"),
    },
    {
        id: 2,
        customerId: 2,
        invoiceId: "INV-2024-002",
        status: OrderStatus.Processing,
        deliveryMethod: "express",
        deliveryCountry: "Belgium",
        deliveryFirstname: "Jamik",
        deliveryLastname: "Tashpulatov",
        deliveryCompany: "Tech Innovations BVBA",
        deliveryAddress: "Rue de la Loi 200",
        deliveryPostalcode: "1000",
        deliveryCity: "Brussels",
        deliveryPhonenumber: "+32 2 234 5678",
        invoiceCountry: "Belgium",
        invoiceFirstname: "Jamik",
        invoiceLastname: "Tashpulatov",
        invoiceCompany: "Tech Innovations BVBA",
        invoiceCOCNumber: "BE0123456789",
        invoiceAddress: "Rue de la Loi 200",
        invoicePostalcode: "1000",
        invoiceCity: "Brussels",
        invoicePhonenumber: "+32 2 234 5678",
        createdAt: new Date("2024-11-09T14:15:00Z"),
    },
    {
        id: 3,
        customerId: 3,
        invoiceId: "INV-2024-003",
        status: OrderStatus.Shipped,
        deliveryMethod: "standard",
        deliveryCountry: "Germany",
        deliveryFirstname: "Maria",
        deliveryLastname: "Schmidt",
        deliveryCompany: "Schmidt Engineering GmbH",
        deliveryAddress: "Alexanderplatz 1",
        deliveryPostalcode: "10178",
        deliveryCity: "Berlin",
        deliveryPhonenumber: "+49 30 345 6789",
        invoiceCountry: "Germany",
        invoiceFirstname: "Maria",
        invoiceLastname: "Schmidt",
        invoiceCompany: "Schmidt Engineering GmbH",
        invoiceCOCNumber: "HRB 123456",
        invoiceAddress: "Alexanderplatz 1",
        invoicePostalcode: "10178",
        invoiceCity: "Berlin",
        invoicePhonenumber: "+49 30 345 6789",
        createdAt: new Date("2024-11-08T09:45:00Z"),
    },
    {
        id: 4,
        customerId: 4,
        invoiceId: "INV-2024-004",
        status: OrderStatus.Paid,
        deliveryMethod: "express",
        deliveryCountry: "France",
        deliveryFirstname: "Pierre",
        deliveryLastname: "Dubois",
        deliveryCompany: "Dubois & Associates SARL",
        deliveryAddress: "Champs-Élysées 100",
        deliveryPostalcode: "75008",
        deliveryCity: "Paris",
        deliveryPhonenumber: "+33 1 456 7890",
        invoiceCountry: "France",
        invoiceFirstname: "Pierre",
        invoiceLastname: "Dubois",
        invoiceCompany: "Dubois & Associates SARL",
        invoiceCOCNumber: "SIREN 123456789",
        invoiceAddress: "Champs-Élysées 100",
        invoicePostalcode: "75008",
        invoiceCity: "Paris",
        invoicePhonenumber: "+33 1 456 7890",
        createdAt: new Date("2024-11-07T16:20:00Z"),
    },
    {
        id: 5,
        customerId: 5,
        invoiceId: "INV-2024-005",
        status: OrderStatus.Cancelled,
        deliveryMethod: "standard",
        deliveryCountry: "United Kingdom",
        deliveryFirstname: "James",
        deliveryLastname: "Wilson",
        deliveryCompany: "Wilson Tech Ltd",
        deliveryAddress: "Baker Street 221B",
        deliveryPostalcode: "NW1 6XE",
        deliveryCity: "London",
        deliveryPhonenumber: "+44 20 7890 1234",
        invoiceCountry: "United Kingdom",
        invoiceFirstname: "James",
        invoiceLastname: "Wilson",
        invoiceCompany: "Wilson Tech Ltd",
        invoiceCOCNumber: "12345678",
        invoiceAddress: "Baker Street 221B",
        invoicePostalcode: "NW1 6XE",
        invoiceCity: "London",
        invoicePhonenumber: "+44 20 7890 1234",
        createdAt: new Date("2024-11-06T11:00:00Z"),
    },
    {
        id: 6,
        customerId: 1,
        invoiceId: "INV-2024-006",
        status: OrderStatus.Finished,
        deliveryMethod: "pickup",
        deliveryCountry: null,
        deliveryFirstname: null,
        deliveryLastname: null,
        deliveryCompany: null,
        deliveryAddress: null,
        deliveryPostalcode: null,
        deliveryCity: null,
        deliveryPhonenumber: null,
        invoiceCountry: "Netherlands",
        invoiceFirstname: "Eddie",
        invoiceLastname: "Lake",
        invoiceCompany: "Lake Solutions BV",
        invoiceCOCNumber: "12345678",
        invoiceAddress: "Keizersgracht 123",
        invoicePostalcode: "1015 CJ",
        invoiceCity: "Amsterdam",
        invoicePhonenumber: "+31 20 123 4567",
        createdAt: new Date("2024-11-05T08:30:00Z"),
    },
] as unknown as z.infer<typeof orderSchema>[];

export default mockOrdersData;
